#!/usr/bin/env bash
# Capture chips' golden trees from the band as it drew before the layouts
# work. Refuses to run on any other hooks. Writes tests/golden/chips.ts.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"; ROOT="$(cd "$HERE/../.." && pwd)"
PLUGIN="$ROOT/plugins/session-usage-band"; OUT="$HERE/out"; mkdir -p "$OUT"
if ! git -C "$ROOT" diff --quiet 40943d3 -- plugins/session-usage-band/hooks; then
  echo "capture.sh: hooks/ differs from 40943d3; the capture must come from the band before the layouts work" >&2
  exit 1
fi
COMMIT="$(git -C "$ROOT" rev-parse HEAD)"
trap 'rm -f "$PLUGIN/tests/zz-golden-capture.test.ts"' EXIT
cp "$HERE/capture.test.ts" "$PLUGIN/tests/zz-golden-capture.test.ts"
START_S=$(date +%s)
claude plugin test "$PLUGIN" > "$OUT/capture.log" 2>&1 || { tail -30 "$OUT/capture.log"; exit 1; }
echo "capture took $(( $(date +%s) - START_S ))s"
python3 - "$OUT/capture.log" "$PLUGIN/tests/golden/chips.ts" "$COMMIT" <<'EOF'
import json, re, sys
log, out, commit = open(sys.argv[1]).read().splitlines(), sys.argv[2], sys.argv[3]
golden = dict(re.match(r'GOLDEN (\S+) (\S+)$', l).groups() for l in log if l.startswith('GOLDEN '))
trees = {m.group(1): json.loads(m.group(2)) for l in log if (m := re.match(r'TREE (\S+) (.+)$', l))}
assert len(golden) == 20 * 2 * 6 * 2, f'expected 480 cases, got {len(golden)}'
assert len(trees) == 10, f'expected 10 trees, got {len(trees)}'
with open(out, 'w') as f:
    f.write(f'// Generated by tools/golden/capture.sh at {commit}, from the band as it\n')
    f.write('// drew before the layouts work. Frozen: a change here must be justified in review.\n\n')
    f.write('export const GOLDEN: Readonly<Record<string, string>> = ' + json.dumps(golden, indent=1, sort_keys=True) + '\n\n')
    f.write('export const GOLDEN_TREES: Readonly<Record<string, unknown>> = ' + json.dumps(trees, sort_keys=True) + '\n')
print(len(golden), 'cases,', len(trees), 'trees')
EOF
grep '^PERF' "$OUT/capture.log"
